In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('openrefine_PHCASES_COVID_04162020_PHnum.csv')

In [3]:
data['Other disease'].unique()

array([nan, 'acute kidney injury, hypertension, diabetes', 'diabetes',
       'hypertension, coronary artery disease, acute kidney injury, chronic kidney disease, diabetes',
       'asthma, diabetes', 'with comorbid (not specified)', 'asthma',
       'hypertension', 'asymptomatic',
       'hypertension, diabetes, valvular heart disease, endocrine condition',
       'hypertension, diabetes', 'status post renal transplant',
       'acute kidney injury', 'community-acquired pneumonia',
       'hypertensive', 'hypertensive cardiovascular disease',
       'diabetes, hypertensive cardiovascular disease, chronic kidney disease, diabetic nephropathy',
       'bronchial asthma',
       'chronic kidney disease, hypertensive nephrosclerosis, ischemic heart disease, peripheral arterial occlusive disease',
       'diabetes, coronary artery disease',
       'acute kidney injury secondary to pre-renal azotemia, cardiomyopathy, ischemic heart disease, diabetes mellitus',
       'hypertension, diabetes

In [4]:
data['Other disease']=data['Other disease'].str.lower()
data['Symptoms']=data['Symptoms'].str.lower()

In [5]:
data['Other disease'].unique()

array([nan, 'acute kidney injury, hypertension, diabetes', 'diabetes',
       'hypertension, coronary artery disease, acute kidney injury, chronic kidney disease, diabetes',
       'asthma, diabetes', 'with comorbid (not specified)', 'asthma',
       'hypertension', 'asymptomatic',
       'hypertension, diabetes, valvular heart disease, endocrine condition',
       'hypertension, diabetes', 'status post renal transplant',
       'acute kidney injury', 'community-acquired pneumonia',
       'hypertensive', 'hypertensive cardiovascular disease',
       'diabetes, hypertensive cardiovascular disease, chronic kidney disease, diabetic nephropathy',
       'bronchial asthma',
       'chronic kidney disease, hypertensive nephrosclerosis, ischemic heart disease, peripheral arterial occlusive disease',
       'diabetes, coronary artery disease',
       'acute kidney injury secondary to pre-renal azotemia, cardiomyopathy, ischemic heart disease, diabetes mellitus',
       'hypertension, diabetes

In [33]:
data['Other disease']=data['Other disease'].str.replace(' asthma','asthma')
data['Other disease']=data['Other disease'].str.replace(' bronchial asthma','asthma')
data['Other disease']=data['Other disease'].str.replace('asthma','asthma')
data['Other disease']=data['Other disease'].str.replace('bronchial asthma','asthma')
data['Other disease']=data['Other disease'].str.replace('bronchialasthma','asthma')
data['Other disease']=data['Other disease'].str.replace(' atherosclerosis','atherosclerosis')
data['Other disease']=data['Other disease'].str.replace(' atherosclerotic cardiovascular disease','atherosclerosis')
data['Other disease']=data['Other disease'].str.replace(' benign prostatic hyperplasia','benign prostatic hyperplasia')
data['Other disease']=data['Other disease'].str.replace(' benign prostatic hypertrophy','benign prostatic hyperplasia')
data['Other disease']=data['Other disease'].str.replace(' cardiac disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' cardiovascular disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' hypertensive cardiovascular disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' coronary artery disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' coronary heart disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' cardiac dysrhythmia','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' cardiomyopathy','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' ischemic heart disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace('hypertensioncardiovascular disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' valvular heart disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace('cardiac disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace('hypertensive cardiovascular disease','cardiovascular disease')
data['Other disease']=data['Other disease'].str.replace(' cerebrovascular accident infarc','cerebrovascular disease infarction')
data['Other disease']=data['Other disease'].str.replace(' cerebrovascular disease infarction','cerebrovascular disease infarction')
data['Other disease']=data['Other disease'].str.replace(' chronic obstructive pulmonary disease','chronic obstructive pulmonary disease')
data['Other disease']=data['Other disease'].str.replace('chronic obstructive pulmonary disease','chronic obstructive pulmonary disease')
data['Other disease']=data['Other disease'].str.replace(' colon cancer','colon cancer')
data['Other disease']=data['Other disease'].str.replace(' dengue','dengue')
data['Other disease']=data['Other disease'].str.replace('  diabetes','diabetes')
data['Other disease']=data['Other disease'].str.replace(' diabetes','diabetes')
data['Other disease']=data['Other disease'].str.replace(' diabetes mellitus','diabetes')
data['Other disease']=data['Other disease'].str.replace(' diabetis mellitus','diabetes')
data['Other disease']=data['Other disease'].str.replace('diabetes','diabetes')
data['Other disease']=data['Other disease'].str.replace(' diabetic ketoacidosis','diabetes')
data['Other disease']=data['Other disease'].str.replace(' diabetic nephropathy','diabetes')
data['Other disease']=data['Other disease'].str.replace(' dyslipidemia','dyslipidemia')
data['Other disease']=data['Other disease'].str.replace(' endocrine condition','endocrine condition')
data['Other disease']=data['Other disease'].str.replace(' hyperthyroidism','hyperthyroidism')
data['Other disease']=data['Other disease'].str.replace('hyperthyroidism','hyperthyroidism')
data['Other disease']=data['Other disease'].str.replace(' hypothyroidism','hypothyroidism')
data['Other disease']=data['Other disease'].str.replace(' impaired fasting glucose','impaired fasting glucose')
data['Other disease']=data['Other disease'].str.replace(' chronic kidney disease','kidney disease')
data['Other disease']=data['Other disease'].str.replace('chronic kidney disease','kidney disease')
data['Other disease']=data['Other disease'].str.replace('renal disease','kidney disease')
data['Other disease']=data['Other disease'].str.replace('chronic kidney disease secondary to hypertension nephrosclerosis','kidney disease')
data['Other disease']=data['Other disease'].str.replace(' kidney disease','kidney disease')
data['Other disease']=data['Other disease'].str.replace('kidney disease secondary tohypertension nephrosclerosis','kidney disease')
data['Other disease']=data['Other disease'].str.replace(' hypertensive nephrosclerosis','kidney disease')
data['Other disease']=data['Other disease'].str.replace(' peripheral arterial occlusive disease','peripheral arterial occlusive disease')
data['Other disease']=data['Other disease'].str.replace('  renal disease','renal disease')
data['Other disease']=data['Other disease'].str.replace(' renal disease','renal disease')
data['Other disease']=data['Other disease'].str.replace('remnal disease','renal disease')
data['Other disease']=data['Other disease'].str.replace(' tongue cancer','tongue cancer')
data['Other disease']=data['Other disease'].str.replace(' acute kidney injury','acute kidney injury')
data['Other disease']=data['Other disease'].str.replace('acute kidney injury','acute kidney injury')
data['Other disease']=data['Other disease'].str.replace('acute kidney injury secondary to pre-renal azotemia','acute renal failure')
data['Other disease']=data['Other disease'].str.replace('acute renal failure','acute renal failure')
data['Other disease']=data['Other disease'].str.replace('asymptomatic','asymptomatic')
data['Other disease']=data['Other disease'].str.replace('breast cancer','breast cancer')
data['Other disease']=data['Other disease'].str.replace('community-acquired pneumonia','community-acquired pneumonia')
data['Other disease']=data['Other disease'].str.replace('with comorbid (not specified)','comorbid_unknown')
data['Other disease']=data['Other disease'].str.replace(' hypertension','hypertension')
data['Other disease']=data['Other disease'].str.replace('hypertension','hypertension')
data['Other disease']=data['Other disease'].str.replace('hypertensive','hypertension')
data['Other disease']=data['Other disease'].str.replace('myocarditis','myocarditis')
data['Other disease']=data['Other disease'].str.replace('none','none')
data['Other disease']=data['Other disease'].str.replace('permanent atrial fibrillation','permanent atrial fibrillation')
data['Other disease']=data['Other disease'].str.replace('prostatic cancer','prostatic cancer')
data['Other disease']=data['Other disease'].str.replace('status post renal transplant','status post renal transplant')
data['Other disease']=data['Other disease'].str.replace('systemic lupus erythematosus','systemic lupus erythematosus')
data['Other disease']=data['Other disease'].str.replace('none','asymptomatic')
data['Symptoms']=data['Symptoms'].str.replace(' body malaise','body malaise')
data['Symptoms']=data['Symptoms'].str.replace(' colds','colds')
data['Symptoms']=data['Symptoms'].str.replace(' comorbidity','comorbidity')
data['Symptoms']=data['Symptoms'].str.replace(' cough','cough')
data['Symptoms']=data['Symptoms'].str.replace(' difficulty in breathing','dyspnea')
data['Symptoms']=data['Symptoms'].str.replace(' dizziness','dizziness')
data['Symptoms']=data['Symptoms'].str.replace(' dysphagia','dysphagia')
data['Symptoms']=data['Symptoms'].str.replace(' headache','headache')
data['Symptoms']=data['Symptoms'].str.replace(' shortness of breath','dyspnea')
data['Symptoms']=data['Symptoms'].str.replace(' sore throat','sore throat')
data['Symptoms']=data['Symptoms'].str.replace('asymptomatic','asymptomatic')
data['Symptoms']=data['Symptoms'].str.replace('cough','cough')
data['Symptoms']=data['Symptoms'].str.replace(' cough','cough')
data['Symptoms']=data['Symptoms'].str.replace('difficulty of breathing','dyspnea')
data['Symptoms']=data['Symptoms'].str.replace('difficulty of breathing','dyspnea')
data['Symptoms']=data['Symptoms'].str.replace('dyspnea','dyspnea')
data['Symptoms']=data['Symptoms'].str.replace('fever','fever')
data['Symptoms']=data['Symptoms'].str.replace('sore throat','sore throat')
data['Other disease']=data['Other disease'].str.replace(' ,',',')
data['Other disease']=data['Other disease'].str.replace(', ',',')
data['Symptoms']=data['Symptoms'].str.replace(' ,',',')
data['Symptoms']=data['Symptoms'].str.replace(', ',',')


In [34]:
data['Other disease'].unique()


array([nan, 'acute kidney injury,hypertension,diabetes', 'diabetes',
       'hypertension,cardiovascular disease,acute kidney injury,kidney disease,diabetes',
       'asthma,diabetes', 'with comorbid (not specified)', 'asthma',
       'hypertension', 'asymptomatic',
       'hypertension,diabetes,cardiovascular disease,endocrine condition',
       'hypertension,diabetes', 'status post renal transplant',
       'acute kidney injury', 'community-acquired pneumonia',
       'cardiovascular disease',
       'diabetes,cardiovascular disease,kidney disease,diabetes',
       'kidney disease,kidney disease,cardiovascular disease,peripheral arterial occlusive disease',
       'diabetes,cardiovascular disease',
       'acute renal failure,cardiovascular disease,cardiovascular disease,diabetes mellitus',
       'hypertension,diabetes,asthma', 'hypertension,colon cancer',
       'hypertension,diabetes,cardiovascular disease',
       'acute kidney injury,benign prostatic hyperplasia',
       'cardio

In [8]:
data['Symptoms'].unique()

array([nan, 'fever,cough,sore throat', 'fever', 'cough', 'cough,dyspnea',
       'fever,sore throat', 'fever,cough', 'cough,comorbidity',
       'cough,sore throat,colds', 'cough,colds',
       'fever,headache,body malaise', 'asymptomatic',
       'cough,body malaise', 'cough,colds,dysphagia',
       'cough,sore throat,headache', 'dyspnea', 'sore throat',
       'fever,cough,dizziness', 'fever,cough,dyspnea'], dtype=object)